services:
  app:
    container_name: hai-duo-app
    image: seunpark/hai-duo-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      db_mysql:
        condition: service_healthy
      db_mongo:
        condition: service_started
    networks:
      - hai-duo-network

  db_mysql:
    container_name: hai-duo-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hai-duo-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db_mongo:
    container_name: hai-duo-mongo
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - hai-duo-network

networks:
  hai-duo-network:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
