server:
  port: 8081

quiz:
  path: ${QUIZ_PATH}

spring:
  application:
    name: hai-duo

  profiles:
    active: prod

  datasource:
    url: ${DB_JDBC_URI}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri: ${MONGODB_URI}

    redis:
      host: localhost
      port: 6379
      enable: false

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  web:
    resources:
      add-mappings: true
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/

graphql:
  path: /graphql
  graphiql:
    enabled: true
    path: /graphiql
    endpoint: /graphql
  schema:
    locations: classpath:graphql/

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
