server:
  port: 8080

spring:
  application:
    name: hai-duo-graphql

  datasource:
    url: ${DB_JDBC_URI}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri: ${MONGODB_URI}

    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

graphql:
  path: /graphql
  graphiql:
    enabled: true
    path: /graphiql
    endpoint: /graphql
  schema:
    locations: classpath:graphql/**

#jwt:
#  secret: your_jwt_secret_key_here
#  expiration: 3600000 # 1 hour (ms)

#cloud:
#  aws:
#    s3:
#      bucket: your-s3-bucket-name
#    credentials:
#      access-key: YOUR_ACCESS_KEY
#      secret-key: YOUR_SECRET_KEY
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
