name: Docker Image Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hai-duo-backend:latest

      - name: Upload .env to EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.ENV_FILE_CONTENT }}" > ~/hai-duo.env

            docker pull ${{ secrets.DOCKER_USERNAME }}/hai-duo-backend:latest

            docker stop hai-duo-app || true
            docker rm hai-duo-app || true

            docker run -d \
              --name hai-duo-app \
              --env-file ~/hai-duo.env \
              -p 8080:8080 \
              ${{ secrets.DOCKER_USERNAME }}/hai-duo-backend:latest
