name: ECR를 통해 AWS Lambda에 배포

on:
  push:
    branches: [ main ]

env:
  REGION: ${{ secrets.AWS_REGION }}                  # AWS 리전 (예: ap-northeast-2)
  ECR_REPO: ${{ secrets.ECR_REPOSITORY }}            # ECR 리포지토리 이름
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}          # ECR 전체 주소
  IMAGE_TAG: latest                                  # 태그는 latest로 고정

jobs:
  deploy:
    runs-on: ubuntu-latest                           # GitHub 호스팅 리눅스 서버에서 실행

    steps:
      - name: GitHub 레포지토리 코드 체크아웃
        uses: actions/checkout@v3

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle로 Spring Boot 빌드
        run: ./gradlew clean build

      - name: AWS 자격 증명 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: ECR에 Docker 로그인
        run: aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Docker 이미지 빌드
        run: docker build -t $ECR_REPO .

      - name: Docker 이미지 태깅
        run: docker tag $ECR_REPO:latest $ECR_REGISTRY/$ECR_REPO:latest

      - name: Docker 이미지 ECR로 푸시
        run: docker push $ECR_REGISTRY/$ECR_REPO:latest
